baseURL = 'https://joshuafurman.github.io/'
languageCode = 'en-us'
title = 'Testing Publishing'
theme = 'github.com/nodejh/hugo-theme-mini'

[params]
author = 'Joshua Furman'
bio = 'Software Engineer'

[social]
github = 'https://github.com/JoshuaFurman'
