baseURL = 'https://joshuafurman.github.io/'
languageCode = 'en-us'
title = 'Furmware'
theme = 'github.com/nodejh/hugo-theme-mini'

[params]
author = 'Joshua Furman'
bio = 'Software Alchemist'

[social]
github = 'https://github.com/JoshuaFurman'
twitter = 'https://twitter.com/furman_josh'
